/**
 * @file known_blacklist_generated.h
 * @brief Auto-generated blacklist of known WiFi and BLE devices
 * 
 * This file is auto-generated by tools/generate_blacklist_from_csv.py
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * Generated from CSV session data in datasets/
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

// WiFi SSID blacklist (case-sensitive exact match)
extern const char* known_wifi_ssids[];
extern const size_t known_wifi_ssids_count;

// WiFi MAC address blacklist (6-byte comparison)
extern const uint8_t known_wifi_macs[][6];
extern const size_t known_wifi_macs_count;

// BLE MAC address blacklist (6-byte comparison)
extern const uint8_t known_ble_macs[][6];
extern const size_t known_ble_macs_count;

// OUI/Prefix blacklist (first 3 bytes)
extern const uint8_t known_ouis[][3];
extern const size_t known_ouis_count;
