#!/usr/bin/env python3
"""
Generate blacklist header files from session CSV files.

This script processes CSV files containing WiFi and BLE device information
and generates C++ header/source files with compile-time blacklists.

Output:
  - include/known_blacklist_generated.h
  - src/known_blacklist_generated.cpp

Usage:
  python3 tools/generate_blacklist_from_csv.py
"""

import csv
import os
import sys
from collections import OrderedDict
from typing import Set, List, Tuple


def validate_mac(mac_str: str) -> Tuple[bool, List[int]]:
    """
    Validate and parse MAC address.
    
    Args:
        mac_str: MAC address string (e.g., "aa:bb:cc:dd:ee:ff")
        
    Returns:
        Tuple of (is_valid, [6 bytes as ints])
    """
    if not mac_str:
        return False, []
    
    # Handle both : and - separators
    mac_str = mac_str.replace('-', ':')
    parts = mac_str.split(':')
    
    if len(parts) != 6:
        return False, []
    
    try:
        bytes_list = [int(p, 16) for p in parts]
        return True, bytes_list
    except ValueError:
        return False, []


def process_csv_files(csv_dir: str) -> Tuple[Set[str], Set[Tuple[int, ...]], Set[Tuple[int, ...]], Set[Tuple[int, ...]]]:
    """
    Process all CSV files and extract unique SSIDs and MACs.
    
    Args:
        csv_dir: Directory containing CSV files
        
    Returns:
        Tuple of (wifi_ssids, wifi_macs, ble_macs, ouis)
    """
    wifi_ssids = set()
    wifi_macs = set()
    ble_macs = set()
    ouis = set()
    
    # BLE/Bluetooth type identifiers
    BLE_TYPES = ['BLE', 'BT']
    
    csv_files = [f for f in os.listdir(csv_dir) if f.endswith('.csv')]
    print(f"Processing {len(csv_files)} CSV files from {csv_dir}")
    
    for csv_file in csv_files:
        filepath = os.path.join(csv_dir, csv_file)
        print(f"  Reading: {csv_file}")
        
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                reader = csv.DictReader(f)
                
                for row in reader:
                    # Determine protocol (wifi vs bluetooth_le)
                    protocol = None
                    
                    # Check if it's BLE/BT (has 'type' column with 'BLE' or 'BT' value)
                    if 'type' in row and row['type'] in BLE_TYPES:
                        protocol = 'bluetooth_le'
                    # Check if it has WiFi-specific columns
                    elif 'ssid' in row and 'netid' in row:
                        # If has ssid but type is BLE/BT, it's BLE with ssid field
                        if 'type' in row and row['type'] in BLE_TYPES:
                            protocol = 'bluetooth_le'
                        else:
                            protocol = 'wifi'
                    
                    # Process WiFi
                    if protocol == 'wifi':
                        # Extract SSID
                        ssid = row.get('ssid', '').strip()
                        if ssid:
                            wifi_ssids.add(ssid)
                        
                        # Extract MAC from 'netid' column
                        mac_str = row.get('netid', '').strip()
                        valid, mac_bytes = validate_mac(mac_str)
                        if valid:
                            mac_tuple = tuple(mac_bytes)
                            wifi_macs.add(mac_tuple)
                            # Add OUI (first 3 bytes)
                            ouis.add(mac_tuple[:3])
                    
                    # Process BLE
                    elif protocol == 'bluetooth_le':
                        # Extract MAC from 'netid' column
                        mac_str = row.get('netid', '').strip()
                        valid, mac_bytes = validate_mac(mac_str)
                        if valid:
                            mac_tuple = tuple(mac_bytes)
                            ble_macs.add(mac_tuple)
                            # Add OUI (first 3 bytes)
                            ouis.add(mac_tuple[:3])
        
        except Exception as e:
            print(f"  WARNING: Error processing {csv_file}: {e}")
            continue
    
    print(f"\nExtracted:")
    print(f"  WiFi SSIDs: {len(wifi_ssids)}")
    print(f"  WiFi MACs: {len(wifi_macs)}")
    print(f"  BLE MACs: {len(ble_macs)}")
    print(f"  OUIs: {len(ouis)}")
    
    return wifi_ssids, wifi_macs, ble_macs, ouis


def generate_header_file(output_path: str):
    """Generate the header file."""
    content = """/**
 * @file known_blacklist_generated.h
 * @brief Auto-generated blacklist of known WiFi and BLE devices
 * 
 * This file is auto-generated by tools/generate_blacklist_from_csv.py
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * Generated from CSV session data in datasets/
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

// WiFi SSID blacklist (case-sensitive exact match)
extern const char* known_wifi_ssids[];
extern const size_t known_wifi_ssids_count;

// WiFi MAC address blacklist (6-byte comparison)
extern const uint8_t known_wifi_macs[][6];
extern const size_t known_wifi_macs_count;

// BLE MAC address blacklist (6-byte comparison)
extern const uint8_t known_ble_macs[][6];
extern const size_t known_ble_macs_count;

// OUI/Prefix blacklist (first 3 bytes)
extern const uint8_t known_ouis[][3];
extern const size_t known_ouis_count;
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Generated: {output_path}")


def generate_source_file(output_path: str, wifi_ssids: Set[str], wifi_macs: Set[Tuple[int, ...]], 
                         ble_macs: Set[Tuple[int, ...]], ouis: Set[Tuple[int, ...]]):
    """Generate the source file with blacklist data."""
    
    # Sort for consistent output
    sorted_ssids = sorted(list(wifi_ssids))
    sorted_wifi_macs = sorted(list(wifi_macs))
    sorted_ble_macs = sorted(list(ble_macs))
    sorted_ouis = sorted(list(ouis))
    
    content = """/**
 * @file known_blacklist_generated.cpp
 * @brief Auto-generated blacklist data
 * 
 * This file is auto-generated by tools/generate_blacklist_from_csv.py
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * Generated from CSV session data in datasets/
 */

#include "known_blacklist_generated.h"

"""
    
    # Generate WiFi SSID array
    content += "// WiFi SSID blacklist (case-sensitive exact match)\n"
    content += "const char* known_wifi_ssids[] = {\n"
    for ssid in sorted_ssids:
        # Escape special characters
        escaped_ssid = ssid.replace('\\', '\\\\').replace('"', '\\"')
        content += f'    "{escaped_ssid}",\n'
    content += "};\n"
    content += f"const size_t known_wifi_ssids_count = {len(sorted_ssids)};\n\n"
    
    # Generate WiFi MAC array
    content += "// WiFi MAC address blacklist (6-byte comparison)\n"
    content += "const uint8_t known_wifi_macs[][6] = {\n"
    for mac in sorted_wifi_macs:
        mac_str = ", ".join([f"0x{b:02x}" for b in mac])
        content += f"    {{{mac_str}}},\n"
    content += "};\n"
    content += f"const size_t known_wifi_macs_count = {len(sorted_wifi_macs)};\n\n"
    
    # Generate BLE MAC array
    content += "// BLE MAC address blacklist (6-byte comparison)\n"
    content += "const uint8_t known_ble_macs[][6] = {\n"
    for mac in sorted_ble_macs:
        mac_str = ", ".join([f"0x{b:02x}" for b in mac])
        content += f"    {{{mac_str}}},\n"
    content += "};\n"
    content += f"const size_t known_ble_macs_count = {len(sorted_ble_macs)};\n\n"
    
    # Generate OUI array
    content += "// OUI/Prefix blacklist (first 3 bytes)\n"
    content += "const uint8_t known_ouis[][3] = {\n"
    for oui in sorted_ouis:
        oui_str = ", ".join([f"0x{b:02x}" for b in oui])
        content += f"    {{{oui_str}}},\n"
    content += "};\n"
    content += f"const size_t known_ouis_count = {len(sorted_ouis)};\n"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Generated: {output_path}")


def main():
    """Main entry point."""
    # Get repository root
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    
    # Paths
    datasets_dir = os.path.join(repo_root, 'datasets')
    header_path = os.path.join(repo_root, 'include', 'known_blacklist_generated.h')
    source_path = os.path.join(repo_root, 'src', 'known_blacklist_generated.cpp')
    
    print("=" * 70)
    print("Blacklist Generator")
    print("=" * 70)
    print(f"Repository root: {repo_root}")
    print(f"Datasets directory: {datasets_dir}")
    print()
    
    if not os.path.exists(datasets_dir):
        print(f"ERROR: Datasets directory not found: {datasets_dir}")
        sys.exit(1)
    
    # Process CSV files
    wifi_ssids, wifi_macs, ble_macs, ouis = process_csv_files(datasets_dir)
    
    # Generate output files
    print()
    generate_header_file(header_path)
    generate_source_file(source_path, wifi_ssids, wifi_macs, ble_macs, ouis)
    
    print()
    print("=" * 70)
    print("Blacklist generation complete!")
    print("=" * 70)


if __name__ == '__main__':
    main()
